// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resturant.DataAcess;

#nullable disable

namespace Resturant.DataAcess.Migrations
{
    [DbContext(typeof(RestContext))]
    partial class RestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Resturant.DataAcess.Models.Category", b =>
                {
                    b.Property<int>("Cat_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cat_Id"));

                    b.Property<string>("Cat_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cat_Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Resturant.DataAcess.Models.Favourite", b =>
                {
                    b.Property<int>("U_Id")
                        .HasColumnType("int");

                    b.Property<int>("Prod_Id")
                        .HasColumnType("int");

                    b.HasKey("U_Id", "Prod_Id");

                    b.HasIndex("Prod_Id");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Resturant.DataAcess.Models.Product", b =>
                {
                    b.Property<int>("Prod_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Prod_Id"));

                    b.Property<int>("Cat_Id")
                        .HasColumnType("int");

                    b.Property<int>("Prod_Amount")
                        .HasColumnType("int");

                    b.Property<string>("Prod_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prod_Price")
                        .HasColumnType("int");

                    b.HasKey("Prod_Id");

                    b.HasIndex("Cat_Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Resturant.DataAcess.Models.User", b =>
                {
                    b.Property<int>("U_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("U_Id"));

                    b.Property<string>("U_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("U_BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("U_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("U_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Resturant.DataAcess.Models.Favourite", b =>
                {
                    b.HasOne("Resturant.DataAcess.Models.Product", "product")
                        .WithMany("favourites")
                        .HasForeignKey("Prod_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Resturant.DataAcess.Models.User", "user")
                        .WithMany("favourites")
                        .HasForeignKey("U_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Resturant.DataAcess.Models.Product", b =>
                {
                    b.HasOne("Resturant.DataAcess.Models.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("Cat_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("Resturant.DataAcess.Models.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Resturant.DataAcess.Models.Product", b =>
                {
                    b.Navigation("favourites");
                });

            modelBuilder.Entity("Resturant.DataAcess.Models.User", b =>
                {
                    b.Navigation("favourites");
                });
#pragma warning restore 612, 618
        }
    }
}
